version: 0.2

phases:
    pre_build:
        commands:
            - cd client
            - npm run build
            - npm install
    build:
        commands:
            - cd client
            - npm run build
            - npm install

artifacts:
    files:
        - "**/*"
    base-directory: client/build
